# Create a program that will play the “cows and bulls” game with the user. The game works like this:
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the
# user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed
# correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many
# “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track
# of the number of guesses the user makes throughout teh game and tell the user at the end.
# Say the number generated by the computer is 1038. An example interaction could look like this:
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
import random

def print_game():
    print("Let's play a game of Cowbull!")
    print("I will generate a number, and you have to guess the numbers one digit at a time.")
    print("For every number in the wrong place, you get a cow. For every one in the right place, you get a bull.")
    print("The game ends when you get 4 bulls!")
    print("Type exit at any prompt to exit.")
    return

def compare(num, user_num):
    cow_bull = {'cow': 0, 'bull': 0}
    for i in range(4):
        if num[i] == user_num[i]:
            cow_bull['cow'] += 1
        else:
            cow_bull['bull'] += 1
    return cow_bull

if __name__ == "__main__":

    print_game()
    random_num = str(random.randint(1000, 9999)) # always will return 4 digit number
    print(random_num)
    count = 0

    while True:
        guess = input("Give me a 4 digit number: ")
        if guess == "exit":
            print("Goodbye")
            break

        count += 1

        cow_bull = compare(random_num, guess)
        
        if list(cow_bull.values())[0] == 4:
            print("Congratulations you got the right number: " + guess + " in " + str(count) + " guesses.")
            break
        else:
            print("You got: " + str(cow_bull))
